# Generated by Django 3.2.5 on 2021-08-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='postcode',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
