# Generated by Django 3.2.6 on 2021-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210818_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
